name: Notify Slack on Issues

on:
  issues:
    types:
      - opened
      - reopened
      - closed
      - edited
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - milestoned
      - demilestoned

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Format and send message to Slack (Incoming Webhook)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          ACTION: ${{ github.event.action }}
          REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          TITLE: ${{ github.event.issue.title }}
          STATE: ${{ github.event.issue.state }}
          URL: ${{ github.event.issue.html_url }}
          SENDER: ${{ github.actor }}
          LABEL: ${{ github.event.label.name }}
          ASSIGNEE: ${{ github.event.assignee.login }}
          MILESTONE: ${{ github.event.issue.milestone.title }}
        run: |
          # Escape quotes in title to keep JSON valid
          ESCAPED_TITLE=$(printf '%s' "$TITLE" | sed 's/"/\\"/g')

          # Build an extra context line depending on action (optional niceties)
          EXTRA=""
          case "$ACTION" in
            labeled) EXTRA=" • label: *${LABEL}*";;
            unlabeled) EXTRA=" • label: *${LABEL}*";;
            assigned) EXTRA=" • assignee: *@${ASSIGNEE}*";;
            unassigned) EXTRA=" • assignee: *@${ASSIGNEE}*";;
            milestoned) EXTRA=" • milestone: *${MILESTONE}*";;
            demilestoned) EXTRA=" • milestone: *${MILESTONE}*";;
          esac

          TEXT="*[${REPO}]* Issue #${NUMBER} *${ACTION}*: \"${ESCAPED_TITLE}\" (${STATE}) by *${SENDER}*${EXTRA}\n${URL}"

          curl -sS -X POST "$SLACK_WEBHOOK_URL" \
            -H 'Content-type: application/json' \
            --data "{\"text\":\"$TEXT\"}"




#name: Notify Slack on Issues
#on:
#  issues:
#    types: [opened, reopened, closed, edited]
#jobs:
#  notify:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Send message to Slack (Incoming Webhook)
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#          ACTION: ${{ github.event.action }}
#          REPO: ${{ github.repository }}
#          NUMBER: ${{ github.event.issue.number }}
#          TITLE: ${{ github.event.issue.title }}
#          STATE: ${{ github.event.issue.state }}
#          URL: ${{ github.event.issue.html_url }}
#          SENDER: ${{ github.actor }}
#        run: |
#          ESCAPED_TITLE=$(printf '%s' "$TITLE" | sed 's/"/\\"/g')
#          TEXT="*[${REPO}]* Issue #${NUMBER} *${ACTION}*: \"${ESCAPED_TITLE}\" (${STATE}) by ${SENDER}\n${URL}"
#          curl -sS -X POST "$SLACK_WEBHOOK_URL" \
#            -H 'Content-type: application/json' \
#            --data "{\"text\":\"$TEXT\"}"
